#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@sdwan[-1]
	add ucitrack sdwan
	set ucitrack.@sdwan[-1].init=sdwan
	commit ucitrack
EOF
chmod +x /etc/init.d/sdwan
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
