#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2020 OpenWrt.org

START=99
USE_PROCD=1

check() {
    if [ ! -z "$checkip" ]; then
        echo ' ' >/tmp/sdwan_check
        cat > /tmp/sdwan_check <<'EOF'
#!/bin/sh
time="$(($(uci -q get sdwan.@sdwan[0].checktime) * 60))"
if [ -z "$time" ]; then
    time=120
    uci -q set sdwan.@sdwan[0].checktime=2
    uci commit sdwan
fi

while true;
do
    if [ "$(uci -q get sdwan.@sdwan[0].enabled)" = "1" ]; then
        /bin/ping -c 3 223.5.5.5 -w 5 >/dev/null 2>&1
        if [ "$?" == "0" ]; then
            if [ ! -z "$(uci -q get sdwan.@sdwan[0].checkip)" ]; then
                online=""
                for ip in $(uci -q get sdwan.@sdwan[0].checkip); do
                    ms=`echo $(/bin/ping -4 $ip -c 2 -w 4 -q) | awk -F '/' '{print $4}'`
                    [ ! -z "$ms" ] && echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 通断检测：${ip} 延迟：${ms}ms " >>/tmp/sdwan.log && online=1
                    [ -z "$ms" ] && echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 通断检测：${ip} 网络中断 " >>/tmp/sdwan.log
                done
                [ "$online" != "1" ] && echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 通断检测：$(uci -q get sdwan.@sdwan[0].checkip) 所有指定IP皆无法ping通,重新启动程序！ " >>/tmp/sdwan.log && /etc/init.d/sdwan restart
            fi
        else
            echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 通断检测：检测到互联网未能成功访问，跳过检测 " >>/tmp/sdwan.log
        fi
    else
        echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 通断检测：程序已关闭，退出检测 " >>/tmp/sdwan.log
        /etc/init.d/sdwan restart
        break
    fi
    sleep $((time))
    [ "$(du -k /log/sdwan.log | cut -f1)" = "1000" ] && echo " " >/tmp/sdwan.log
done
EOF
        chmod +x /tmp/sdwan_check
        procd_open_instance
       	procd_set_param respawn
       	procd_set_param command /tmp/sdwan_check
       	procd_close_instance
    fi
}

get_tz() {
	SET_TZ=""
	[ -e "/etc/localtime" ] && return
	for tzfile in /etc/TZ /var/etc/TZ
	do
		[ -e "$tzfile" ] || continue
		tz="$(cat $tzfile 2>/dev/null)"
	done
	[ -z "$tz" ] && return
	SET_TZ=$tz
}

check_bin() {
	curltest=`which curl`
	user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
	#github加速地址，一行一个 你可以自建改为你自己的
	proxys="
	https://ghproxy.net/
	https://gh-proxy.com/
	https://cdn.gh-proxy.com/
	https://ghfast.top/
	"
	if [ -z "$curltest" ] || [ ! -s "`which curl`" ] ; then
       	tag="$( wget --no-check-certificate -T 5 -t 3 --user-agent "$user_agent" --max-redirect=0 --output-document=-  https://api.github.com/zzxym/sdwan/releases/latest  2>&1 | grep 'tag_name' | cut -d\" -f4 )"
       	[ -z "$tag" ] && tag="$( wget --no-check-certificate -T 5 -t 3 --user-agent "$user_agent" --quiet --output-document=-  https://api.github.com/zzxym/sdwan/releases/latest  2>&1 | grep 'tag_name' | cut -d\" -f4 )"
   	 else
       	tag="$( curl -k --connect-timeout 3 --user-agent "$user_agent"  https://api.github.com/zzxym/sdwan/releases/latest  2>&1 | grep 'tag_name' | cut -d\" -f4 )"
       	[ -z "$tag" ] && tag="$( curl -Lk --connect-timeout 3 --user-agent "$user_agent" -s  https://api.github.com/zzxym/sdwan/releases/latest  2>&1 | grep 'tag_name' | cut -d\" -f4 )"
   	fi
	[ -z "$tag"] && tag=v2.4.3
	echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 开始在线下载${tag}版本，${proxy}https://github.com/zzxym/sdwan/releases/download/${tag}/sdwan-linux-${cpucore}-${tag}.zip下载较慢耐心等候" >>/tmp/sdwan.log
	echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 开始在线下载${tag}版本，${proxy}https://github.com/zzxym/sdwan/releases/download/${tag}/sdwan-linux-${cpucore}-${tag}.zip下载较慢耐心等候" >>/tmp/sdwanweb.log
        mkdir -p "$path"
	for proxy in $proxys ; do
	        if curl -L -k -o /tmp/sdwan.zip --connect-timeout 10 --retry 3 "${proxy}https://github.com/zzxym/sdwan/releases/download/${tag}/sdwan-linux-${cpucore}-${tag}.zip" || \
		wget --no-check-certificate --timeout=10 --tries=3 -O /tmp/sdwan.zip "${proxy}https://github.com/zzxym/sdwan/releases/download/${tag}/sdwan-linux-${cpucore}-${tag}.zip" ; then
			unzip -j -q -o /tmp/sdwan.zip -d /tmp
	         	chmod +x /tmp/sdwan-core /tmp/sdwan-cli /tmp/sdwan-web /tmp/sdwan-web-embed || true
	         	if [ "$(uci -q get sdwan.@sdwan[0].enabled)" = "1" ] ; then
	         		mv -f /tmp/sdwan-core ${path}/
	         		mv -f /tmp/sdwan-cli ${path}/
	         		chmod +x "$sdwanbin"
	         		if [ "$($sdwanbin -h 2>&1 | wc -l)" -gt 3 ] ; then
                   			echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : ${sdwanbin} 下载成功" >>/tmp/sdwan.log
                 		else
                    			echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : ${proxy}https://github.com/zzxym/sdwan/releases/download/${tag}/sdwan-linux-${cpucore}-${tag}.zip 下载不完整，请手动下载上传程序" >>/tmp/sdwan.log
                 		fi
	         	fi
	         	if [ "$(uci -q get sdwan.@sdwanweb[0].enabled)" = "1" ] ; then
	         		mv -f /tmp/sdwan-web-embed ${webbin} || true
	         		chmod +x "$webbin"
	         		if [ "$($webbin -h 2>&1 | wc -l)" -gt 3 ] ; then
					echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : ${webbin} 下载成功" >>/tmp/sdwanweb.log
                 		else
					echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : ${proxy}https://github.com/zzxym/sdwan/releases/download/${tag}/sdwan-linux-${cpucore}-${tag}.zip 下载不完整，请手动下载上传程序" >>/tmp/sdwanweb.log
                 		fi
	         	fi
                 	
                	rm -rf /tmp/sdwan.zip 
			break
 		 else
			echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : ${proxy}https://github.com/zzxym/sdwan/releases/download/${tag}/sdwan-linux-${cpucore}-${tag}.zip 下载失败，请手动下载上传程序" >>/tmp/sdwan.log
			echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : ${proxy}https://github.com/zzxym/sdwan/releases/download/${tag}/sdwan-linux-${cpucore}-${tag}.zip 下载失败，请手动下载上传程序" >>/tmp/sdwanweb.log
		fi
	done
}

check_config() {
		   config_file="/etc/sdwan/config.toml"
                   instance_name=$(cat $config_file | grep "instance_name =" | awk '{print $3}'| tr -d '" ')
                   socks_port=$(cat $config_file | grep "socks5_proxy" | awk -F ":" '{print $3}'| tr -d '" ')
                   [ -z "$(grep -F 'listeners = []' $config_file)" ] && listenermode="ON"
                   tcp_port=$(grep -oE '"tcp://(\[::\]|0\.0\.0\.0):[0-9]+"' "$config_file" | head -n1 | sed -E 's/.*:([0-9]+)"/\1/')
                   udp_port=$(grep -oE '"udp://(\[::\]|0\.0\.0\.0):[0-9]+"' "$config_file" | head -n1 | sed -E 's/.*:([0-9]+)"/\1/')
                   ws_port=$(grep -oE '"ws://(\[::\]|0\.0\.0\.0):[0-9]+"' "$config_file" | head -n1 | sed -E 's/.*:([0-9]+)"/\1/')
                   wss_port=$(grep -oE '"wss://(\[::\]|0\.0\.0\.0):[0-9]+"' "$config_file" | head -n1 | sed -E 's/.*:([0-9]+)"/\1/')
                   wg_port=$(grep -oE '"wg://(\[::\]|0\.0\.0\.0):[0-9]+"' "$config_file" | head -n1 | sed -E 's/.*:([0-9]+)"/\1/')
                   quic_port=$(grep -oE '"quic://(\[::\]|0\.0\.0\.0):[0-9]+"' "$config_file" | head -n1 | sed -E 's/.*:([0-9]+)"/\1/')
                   tunname=$(cat $config_file | grep "dev_name =" | awk '{print $3}'| tr -d '", ')
                   proxy_network=$(grep -F '[[proxy_network]]' $config_file)
                   wireguard_port=$(cat $config_file | grep "wireguard_listen = " | awk -F ":" '{print $2}'| tr -d '/", ')
                   log="$(uci -q get sdwan.@sdwan[0].log || echo off)"          
                   procd_open_instance
                   get_tz
		   [ -z "$SET_TZ" ] || procd_set_param env TZ="$SET_TZ"
		   procd_set_param command /bin/sh -c "
			${sdwanbin} -c ${config_file} --console-log-level ${log} >> /tmp/sdwan.log 2>&1 &
		SDWAN_CORE_PID=\$!
		{
			while true; do
				LOG_SIZE=\$(ls -l /tmp/sdwan.log | awk '{print int(\$5/1024)}')
				if [ \$LOG_SIZE -gt 5120 ]; then
					tail -n 500 /tmp/sdwan.log > /tmp/sdwan.log.tmp
					mv /tmp/sdwan.log.tmp /tmp/sdwan.log
				fi
				sleep 300
			done
		} &
		LOG_MANAGEMENT_PID=\$!
		trap "kill -TERM \$SDWAN_CORE_PID; kill -TERM \$LOG_MANAGEMENT_PID; exit" SIGINT SIGTERM EXIT
		wait \$SDWAN_CORE_PID
		   "
		   echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 运行 ${sdwanbin} -c ${config_file}" >>/tmp/sdwan.log
}

get_etconfig() {
		web_config="$(uci -q get sdwan.@sdwan[0].web_config)"
		network_name="$(uci -q get sdwan.@sdwan[0].network_name)"
		network_secret="$(uci -q get sdwan.@sdwan[0].network_secret)"
		ip_dhcp="$(uci -q get sdwan.@sdwan[0].ip_dhcp || echo 0)"
		ipaddr="$(uci -q get sdwan.@sdwan[0].ipaddr)"
		ip6addr="$(uci -q get sdwan.@sdwan[0].ip6addr)"
		external_node="$(uci -q get sdwan.@sdwan[0].external_node)"
		proxy_network="$(uci -q get sdwan.@sdwan[0].proxy_network)"
		rpc_portal="$(uci -q get sdwan.@sdwan[0].rpc_portal || echo 15888)"
		rpc_portal_whitelist="$(uci -q get sdwan.@sdwan[0].rpc_portal_whitelist)"
		listenermode="$(uci -q get sdwan.@sdwan[0].listenermode)"
		tunname="$(uci -q get sdwan.@sdwan[0].tunname)"
		relay_network="$(uci -q get sdwan.@sdwan[0].relay_network || echo 0)"
		tcp_port="$(uci -q get sdwan.@sdwan[0].tcp_port)"
		ws_port="$(uci -q get sdwan.@sdwan[0].ws_port)"
		wss_port="$(uci -q get sdwan.@sdwan[0].wss_port)"
		wg_port="$(uci -q get sdwan.@sdwan[0].wg_port)"
		quic_port="$(uci -q get sdwan.@sdwan[0].quic_port)"
		peeradd="$(uci -q get sdwan.@sdwan[0].peeradd)"
		desvice_name="$(uci -q get sdwan.@sdwan[0].desvice_name)"
		[ -z "$desvice_name" ] || desvice_name=$(echo "$desvice_name" | sed 's/[\\$`"()|><&;]/\\&/g')
		instance_name="$(uci -q get sdwan.@sdwan[0].instance_name)"
		vpn_portal="$(uci -q get sdwan.@sdwan[0].vpn_portal)"
		mtu="$(uci -q get sdwan.@sdwan[0].mtu)"
		default_protocol="$(uci -q get sdwan.@sdwan[0].default_protocol)"
		disable_encryption="$(uci -q get sdwan.@sdwan[0].disable_encryption || echo 0)"
		whitelist="$(uci -q get sdwan.@sdwan[0].whitelist)"
		multi_thread="$(uci -q get sdwan.@sdwan[0].multi_thread || echo 0)"
		multi_thread_count="$(uci -q get sdwan.@sdwan[0].multi_thread_count)"
		disable_ipv6="$(uci -q get sdwan.@sdwan[0].disable_ipv6 || echo 0)"
		latency_first="$(uci -q get sdwan.@sdwan[0].latency_first || echo 0)"
		exit_node="$(uci -q get sdwan.@sdwan[0].exit_node || echo 0)"
		smoltcp="$(uci -q get sdwan.@sdwan[0].smoltcp || echo 0)"
		exit_nodes="$(uci -q get sdwan.@sdwan[0].exit_nodes || echo 0)"
		no_tun="$(uci -q get sdwan.@sdwan[0].no_tun || echo 0)"
		manual_routes="$(uci -q get sdwan.@sdwan[0].manual_routes)"
		log="$(uci -q get sdwan.@sdwan[0].log || echo off)"
		check="$(uci -q get sdwan.@sdwan[0].check || echo 0)"
		disable_p2p="$(uci -q get sdwan.@sdwan[0].disable_p2p || echo 0)"
		disable_udp="$(uci -q get sdwan.@sdwan[0].disable_udp || echo 0)"
		relay_all="$(uci -q get sdwan.@sdwan[0].relay_all || echo 0)"
		checkip="$(uci -q get sdwan.@sdwan[0].checkip)"
		socks_port="$(uci -q get sdwan.@sdwan[0].socks_port)"
		comp="$(uci -q get sdwan.@sdwan[0].comp || echo none)"
		mapped_listeners="$(uci -q get sdwan.@sdwan[0].mapped_listeners)"
		bind_device="$(uci -q get sdwan.@sdwan[0].bind_device || echo 0)"
		kcp_proxy="$(uci -q get sdwan.@sdwan[0].kcp_proxy || echo 0)"
		kcp_input="$(uci -q get sdwan.@sdwan[0].kcp_input || echo 0)"
		proxy_forward="$(uci -q get sdwan.@sdwan[0].proxy_forward || echo 0)"
		port_forward="$(uci -q get sdwan.@sdwan[0].port_forward)"
		accept_dns="$(uci -q get sdwan.@sdwan[0].accept_dns || echo 0)"
		private_mode="$(uci -q get sdwan.@sdwan[0].private_mode || echo 0)"
		quic_proxy="$(uci -q get sdwan.@sdwan[0].quic_proxy || echo 0)"
		quic_input="$(uci -q get sdwan.@sdwan[0].quic_input || echo 0)"
		foreign_relay_bps_limit="$(uci -q get sdwan.@sdwan[0].foreign_relay_bps_limit)"
		extra_args="$(uci -q get sdwan.@sdwan[0].extra_args)"
		encryption_algorithm="$(uci -q get sdwan.@sdwan[0].encryption_algorithm)"
}

set_firewall() {
		
			if [ ! -z "$tcp_port" ] ; then
		    		echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 添加防火墙规则 sdwan_tcp_udp 放行端口 ${tcp_port} " >>/tmp/sdwan.log
                    		uci -q delete firewall.sdwan_tcp_udp
		    		uci set firewall.sdwan_tcp_udp=rule
		    		uci set firewall.sdwan_tcp_udp.name="sdwan_tcp_udp"
		    		uci set firewall.sdwan_tcp_udp.target="ACCEPT"
		    		uci set firewall.sdwan_tcp_udp.src="wan"
		    		uci set firewall.sdwan_tcp_udp.proto="tcp udp"
		    		uci set firewall.sdwan_tcp_udp.dest_port="$tcp_port"
		    		uci set firewall.sdwan_tcp_udp.enabled="1"
		 	fi
		 	if [ ! -z "$udp_port" ] ; then
		      		echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 添加防火墙规则 sdwan_udp 放行UDP端口 ${udp_port} " >>/tmp/sdwan.log
                      		uci -q delete firewall.sdwan_udp
		      		uci set firewall.sdwan_udp=rule
		      		uci set firewall.sdwan_udp.name="sdwan_udp"
		      		uci set firewall.sdwan_udp.target="ACCEPT"
		      		uci set firewall.sdwan_udp.src="wan"
		      		uci set firewall.sdwan_udp.proto="udp"
		      		uci set firewall.sdwan_udp.dest_port="$udp_port"
		      		uci set firewall.sdwan_udp.enabled="1"
	           	fi
                 	if [ ! -z "$wss_port" ] ; then
		   		echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 添加防火墙规则 sdwan_wss 放行端口 ${wss_port} " >>/tmp/sdwan.log
		    		uci -q delete firewall.sdwan_wss
		    		uci set firewall.sdwan_wss=rule
		    		uci set firewall.sdwan_wss.name="sdwan_wss"
		    		uci set firewall.sdwan_wss.target="ACCEPT"
		    		uci set firewall.sdwan_wss.src="wan"
		    		uci set firewall.sdwan_wss.proto="tcp"
		    		uci set firewall.sdwan_wss.dest_port="$wss_port"
		    		uci set firewall.sdwan_wss.enabled="1"
		 	fi
                   	if [ ! -z "$ws_port" ] ; then
		    		echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 添加防火墙规则 sdwan_ws 放行端口 ${ws_port} " >>/tmp/sdwan.log
		    		uci -q delete firewall.sdwan_ws
		    		uci set firewall.sdwan_ws=rule
		    		uci set firewall.sdwan_ws.name="sdwan_ws"
		   		uci set firewall.sdwan_ws.target="ACCEPT"
		    		uci set firewall.sdwan_ws.src="wan"
		    		uci set firewall.sdwan_ws.proto="tcp"
		    		uci set firewall.sdwan_ws.dest_port="$ws_port"
		    		uci set firewall.sdwan_ws.enabled="1"
		   	fi
                   	if [ ! -z "$wg_port" ] ; then
		    		echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 添加防火墙规则 sdwan_wg 放行端口 ${wg_port} " >>/tmp/sdwan.log
		    		uci -q delete firewall.sdwan_wg
		    		uci set firewall.sdwan_wg=rule
		    		uci set firewall.sdwan_wg.name="sdwan_wg"
		    		uci set firewall.sdwan_wg.target="ACCEPT"
		    		uci set firewall.sdwan_wg.src="wan"
		    		uci set firewall.sdwan_wg.proto="udp"
		    		uci set firewall.sdwan_wg.dest_port="$wg_port"
		    		uci set firewall.sdwan_wg.enabled="1"
		   	fi
		   	if [ ! -z "$quic_port" ] ; then
		    		echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 添加防火墙规则 sdwan_quic 放行端口 ${quic_port} " >>/tmp/sdwan.log
		    		uci -q delete firewall.sdwan_quic
		    		uci set firewall.sdwan_quic=rule
		    		uci set firewall.sdwan_quic.name="sdwan_quic"
		    		uci set firewall.sdwan_quic.target="ACCEPT"
		    		uci set firewall.sdwan_quic.src="wan"
		    		uci set firewall.sdwan_quic.proto="tcp udp"
		    		uci set firewall.sdwan_quic.dest_port="$quic_port"
		    		uci set firewall.sdwan_quic.enabled="1"
		   	fi
                
		# 设置默认网卡名称并检查是否已存在，实现递增逻辑
		if [ -z "$tunname" ]; then
			tunname="sdwan0"
			# 检查是否已存在该网卡名称，如果存在则递增数字直到找到可用名称
			while ip link show "$tunname" >/dev/null 2>&1; do
				num=${tunname#sdwan}
				num=$((num + 1))
				tunname="sdwan$num"
			done
		fi
                uci -q delete network.sdwan >/dev/null 2>&1
	        if [ -z "$(uci -q get network.sdwan)" ];  then				
		       uci set network.sdwan='interface'
                       if [ -z "$ipaddr" ]; then
				uci set network.sdwan.proto='none'
			else
				uci set network.sdwan.proto='static'
				uci set network.sdwan.ipaddr=$ipaddr
				uci set network.sdwan.netmask='255.0.0.0'
		       fi
		       echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 添加网络接口 sdwan 绑定虚拟接口 ${tunname}" >>/tmp/sdwan.log
                       uci set network.sdwan.device="$tunname"
                       uci set network.sdwan.ifname="$tunname"
		fi
		if [ -z "$(uci -q get firewall.sdwanzone)" ];  then
				echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 添加防火墙规则，放行网络接口 sdwan 允许出入转发，开启IP动态伪装 MSS钳制" >>/tmp/sdwan.log
				uci set firewall.sdwanzone='zone'
				uci set firewall.sdwanzone.input='ACCEPT'
				uci set firewall.sdwanzone.output='ACCEPT'
				uci set firewall.sdwanzone.forward='ACCEPT'
				uci set firewall.sdwanzone.masq='1'
                                uci set firewall.sdwanzone.mtu_fix='1'
				uci set firewall.sdwanzone.name='sdwan'
				uci set firewall.sdwanzone.network='sdwan'
		fi
		et_forward="$(uci -q get sdwan.@sdwan[0].et_forward)"
		if [ "${et_forward//etfwlan/}" != "$et_forward" ]; then
			echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 允许从虚拟网络 sdwan 到局域网 lan 的流量" >>/tmp/sdwan.log
			uci set firewall.sdwanfwlan=forwarding
			uci set firewall.sdwanfwlan.dest='lan'
			uci set firewall.sdwanfwlan.src='sdwan'
		else
			uci -q delete firewall.sdwanfwlan
		fi
		if [ "${et_forward//etfwwan/}" != "$et_forward" ]; then
			echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 允许从虚拟网络 sdwan 到广域网 wan 的流量" >>/tmp/sdwan.log
			uci set firewall.sdwanfwwan=forwarding
			uci set firewall.sdwanfwwan.dest='wan'
			uci set firewall.sdwanfwwan.src='sdwan'
		else
			uci -q delete firewall.sdwanfwwan
		fi
                if [ "${et_forward//lanfwet/}" != "$et_forward" ]; then
			echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 允许从局域网 lan 到虚拟网络 sdwan 的流量" >>/tmp/sdwan.log
			uci set firewall.lanfwsdwan=forwarding
			uci set firewall.lanfwsdwan.dest='sdwan'
			uci set firewall.lanfwsdwan.src='lan'
		else
			uci -q delete firewall.lanfwsdwan
		fi
                if [ "${et_forward//wanfwet/}" != "$et_forward" ]; then
			echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 允许从广域网 wan 到虚拟网络 sdwan 的流量" >>/tmp/sdwan.log
			uci set firewall.wanfwsdwan=forwarding
			uci set firewall.wanfwsdwan.dest='sdwan'
			uci set firewall.wanfwsdwan.src='wan'
		else
			uci -q delete firewall.wanfwsdwan
		fi
}

start_sdwan() {
                sdwanbin="$(uci -q get sdwan.@sdwan[0].sdwanbin)"
		[ -z "$sdwanbin" ] && sdwanbin="/usr/bin/sdwan-core" && uci -q set sdwan.@sdwan[0].sdwanbin=/usr/bin/sdwan-core
                sdwancmd="$(uci -q get sdwan.@sdwan[0].sdwancmd)"
                echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : sdwan-core_${cpucore}开始启动" >>/tmp/sdwan.log
                path=$(dirname "$sdwanbin")
                if [[ -f /tmp/sdwan-core || -f /tmp/sdwan-cli ]] && [[ "${path:0:4}" != "/tmp" ]]; then
                   chmod +x /tmp/sdwan-core 2>/dev/null
                   chmod +x /tmp/sdwan-cli 2>/dev/null
		   mkdir -p "$path"
                   echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 找到上传的程序/tmp/sdwan-core，替换为$sdwanbin " >>/tmp/sdwan.log
                   upsize="$(du -k /tmp/sdwan-core | cut -f1)"
                   result=$(expr $size - $upsize)
                   [ -z "$size"] && echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 获取可用空间失败，请使用ssh手动上传至 ${sdwanbin} ${path}/sdwan-cli" >>/tmp/sdwan.log
                   if [ "$(($(/tmp/sdwan-core -h 2>&1 | wc -l)))" -gt 3 ] && [ "$result" -gt 1000 ] ; then
                     	mv -f /tmp/sdwan-core "$sdwanbin" 2>/dev/null
                     	mv -f /tmp/sdwan-cli "${path}/sdwan-cli" 2>/dev/null
                    else
		     	if [ -z "$size" ] && [ "$(($(/tmp/sdwan-core -h 2>&1 | wc -l)))" -gt 3 ] ; then
				mv -f /tmp/sdwan-core "$sdwanbin" 2>/dev/null
                     		mv -f /tmp/sdwan-cli "${path}/sdwan-cli" 2>/dev/null
		     	fi
                        echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 无法替换，上传的程序不完整或自定义路径的可用空间不足，当前空间剩余${size}kb" >>/tmp/sdwan.log
                   fi
                fi
                if [ ! -f "$sdwanbin" ] && [ "$size" -lt 5000 ] && [ ! -z "$size" ] ; then
                    echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 自定义程序路径的可用空间不足，当前可用空间剩余${size}kb,自动切换为内存/tmp/sdwan-core" >>/tmp/sdwan.log
                    sed -i "/sdwanbin/c option sdwanbin '/tmp/sdwan-core' " /etc/config/sdwan 
                    sdwanbin=/tmp/sdwan-core
                fi
                if [ -f "$sdwanbin" ] ; then
			if [ ! -x "$sdwanbin" ] ; then
				chmod +x "$sdwanbin" 
                		chmod +x ${path}/sdwan-cli
			fi
		fi
		if [ ! -f "$sdwanbin" ] || [ "$(($($sdwanbin -h 2>&1 | wc -l)))" -lt 3 ] ; then
			echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : $sdwanbin 不存在或程序不完整，开始在线下载..." >>/tmp/sdwan.log
                	check_bin
		fi
                
                ver="$($sdwanbin -V | awk {'print $2'} | tr -d '~')"
                [ ! -z "$ver" ] && echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : ${sdwanbin}当前版本号-${ver} " >>/tmp/sdwan.log
                pgrep -f sdwan_check | xargs kill -9 >/dev/null 2>&1
		
                ps | grep 'sdwan-core' | grep -v grep | awk '{print $1}' | xargs kill >/dev/null 2>&1
                ps | grep 'sdwan-core' | grep -v grep | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
          	if [ "$sdwancmd" = "config" ] ; then 
			#配置文件启动方式
                	check_config  
         	else
			get_etconfig
			procd_open_instance "sdwan_core"
			get_tz
			[ -z "$SET_TZ" ] || procd_set_param env TZ="$SET_TZ"
			core_cmd=""
			if [ "$sdwancmd" = "sdwancmd" ] ; then
				#默认方式启动
				[ -z "$network_name" ] || core_cmd="${core_cmd} --network-name $network_name"
				[ -z "$network_secret" ] || core_cmd="${core_cmd} --network-secret $network_secret"
				[ -z "$ipaddr" ] || core_cmd="${core_cmd} -i $ipaddr"
				[ -z "$ip6addr" ] || core_cmd="${core_cmd} --ipv6 $ip6addr"
				[ "$ip_dhcp" = "0" ] || core_cmd="${core_cmd} -d"
				if [ ! -z "$peeradd" ] ; then
                  			if [[ "$(grep "list peeradd" /etc/config/sdwan | awk '{print $3}' | wc -l ) " -eq 1 ]]; then
                    				core_cmd="${core_cmd} -p $peeradd"
                  			else
                    				for peeraddr in $(cat /etc/config/sdwan | grep 'list peeradd'  | awk -F 'list peeradd' '{print $2}' | sed "s/'/\n/g" | tr -d " ' "); do
                    					core_cmd="${core_cmd} -p $peeraddr"
                   				done
                   			fi
                		fi
                		if [ ! -z "$proxy_network" ] ; then
                  			if [[ "$(grep "list proxy_network" /etc/config/sdwan | awk '{print $3}' | wc -l ) " -eq 1 ]]; then
                    				core_cmd="${core_cmd} -n $proxy_network"
                  			else
                    				for proxy_networks in $(cat /etc/config/sdwan | grep 'list proxy_network'  | awk -F 'list proxy_network' '{print $2}' | sed "s/'/\n/g" | tr -d " ' "); do
                    					core_cmd="${core_cmd} -n $proxy_networks"
                   				done
                   			fi
                		fi
                		if [ ! -z "$exit_nodes" ] ; then
                  			if [[ "$(grep "list exit_nodes" /etc/config/sdwan | awk '{print $3}' | wc -l ) " -eq 1 ]]; then
                    				core_cmd="${core_cmd} --exit-nodes $exit_nodes"
                  			else
                    				for exit_nodeadds in $(cat /etc/config/sdwan | grep 'list exit_nodes'  | awk -F 'list exit_nodes' '{print $2}' | sed "s/'/\n/g" | tr -d " ' "); do
                    					core_cmd="${core_cmd} --exit-nodes $exit_nodeadds"
                   				done
                   			fi
                		fi
                		if [ ! -z "$manual_routes" ] ; then
                  			if [[ "$(grep "list manual_routes" /etc/config/sdwan | awk '{print $3}' | wc -l ) " -eq 1 ]]; then
                    				core_cmd="${core_cmd} --manual-routes $manual_routes"
                  			else
                    				for manual_routeadds in $(cat /etc/config/sdwan | grep 'list manual_routes'  | awk -F 'list manual_routes' '{print $2}' | sed "s/'/\n/g" | tr -d " ' "); do
                    					core_cmd="${core_cmd} --manual-routes $manual_routeadds"
                   				done
                   			fi
                		fi
                		if [ "$relay_network" = "1" ] ; then
                			if [ ! -z "$whitelist" ] ; then
                  				if [[ "$(grep "list whitelist" /etc/config/sdwan | awk '{print $3}' | wc -l ) " -eq 1 ]]; then
                    					core_cmd="${core_cmd} --relay-network-whitelist $whitelist"
                  				else
                    					for whitelists in $(cat /etc/config/sdwan | grep 'list whitelist'  | awk -F 'list whitelist' '{print $2}' | sed "s/'/\n/g" | tr -d " ' "); do
                    						core_cmd="${core_cmd} --relay-network-whitelist $whitelists"
                   					done
                   				fi
                   			else
                   				core_cmd="${core_cmd} --relay-network-whitelist"
                			fi
                		fi
				if [ ! -z "$mapped_listeners" ] ; then
                  			if [[ "$(grep "list mapped_listeners" /etc/config/sdwan | awk '{print $3}' | wc -l ) " -eq 1 ]]; then
                    				core_cmd="${core_cmd} --mapped-listeners $mapped_listeners"
                  			else
                    				for mapped_listener in $(cat /etc/config/sdwan | grep 'list mapped_listeners'  | awk -F 'list mapped_listeners' '{print $2}' | sed "s/'/\n/g" | tr -d " ' "); do
                    					core_cmd="${core_cmd} --mapped-listeners $mapped_listener"
                   				done
                   			fi
                		fi
                		if [ ! -z "$port_forward" ] ; then
                  			if [[ "$(grep "list port_forward" /etc/config/sdwan | awk '{print $3}' | wc -l ) " -eq 1 ]]; then
                    				core_cmd="${core_cmd} --port-forward $port_forward"
                  			else
                    				for port_forwards in $(cat /etc/config/sdwan | grep 'list port_forward'  | awk -F 'list port_forward' '{print $2}' | sed "s/'/\n/g" | tr -d " ' "); do
                    					core_cmd="${core_cmd} --port-forward $port_forwards"
                   				done
                   			fi
                		fi
				[ -z "$rpc_portal" ] || core_cmd="${core_cmd} -r $rpc_portal"
				[ -z "$rpc_portal_whitelist" ] || core_cmd="${core_cmd} --rpc-portal-whitelist $rpc_portal_whitelist"
				[ -z "$tcp_port" ] || core_cmd="${core_cmd} -l tcp:$tcp_port"
				[ -z "$tcp_port" ] || core_cmd="${core_cmd} -l udp:$tcp_port"
				[ -z "$ws_port" ] || core_cmd="${core_cmd} -l ws:$ws_port"
				[ -z "$wss_port" ] || core_cmd="${core_cmd} -l wss:$wss_port"
				[ -z "$wg_port" ] || core_cmd="${core_cmd} -l wg:$wg_port"
				[ -z "$quic_port" ] || core_cmd="${core_cmd} -l quic:$quic_port"
                		[ -z "$external_node" ] || core_cmd="${core_cmd} -e $external_node"
				[ "$listenermode" = "ON" ] || core_cmd="${core_cmd} --no-listener"
				[ -z "$desvice_name" ] || core_cmd="${core_cmd} --hostname $desvice_name"
				[ -z "$instance_name" ] || core_cmd="${core_cmd} -m $instance_name"
				[ -z "$vpn_portal" ] || core_cmd="${core_cmd} --vpn-portal $vpn_portal"
				[ -z "$mtu" ] || core_cmd="${core_cmd} --mtu $mtu"
				[ "$default_protocol" = "-" ] || core_cmd="${core_cmd} --default-protocol $default_protocol"
				[ -z "$tunname" ] || core_cmd="${core_cmd} --dev-name $tunname"
				[ "$disable_encryption" = "0" ] || core_cmd="${core_cmd} -u"
				[ "$multi_thread" = "0" ] || core_cmd="${core_cmd} --multi-thread"
				[ -z "$multi_thread_count" ] || core_cmd="${core_cmd} --multi-thread-count $multi_thread_count"
				[ "$no_tun" = "0" ] || core_cmd="${core_cmd} --no-tun"
				[ "$smoltcp" = "0" ] || core_cmd="${core_cmd} --use-smoltcp"
				[ "$disable_ipv6" = "0" ] || core_cmd="${core_cmd} --disable-ipv6"
				[ "$latency_first" = "0" ] || core_cmd="${core_cmd} --latency-first"
				[ "$exit_node" = "0" ] || core_cmd="${core_cmd} --enable-exit-node"
              	  		[ "$disable_p2p" = "0" ] || core_cmd="${core_cmd} --disable-p2p"
                		[ "$disable_udp" = "0" ] || core_cmd="${core_cmd} --disable-udp-hole-punching"
                		[ "$relay_all" = "0" ] || core_cmd="${core_cmd} --relay-all-peer-rpc"
                		[ -z "$socks_port" ] || core_cmd="${core_cmd} --socks5 $socks_port"
				[ "$comp" = "none" ] || core_cmd="${core_cmd} --compression $comp"
				[ "$bind_device" = "0" ] || core_cmd="${core_cmd} --bind-device true"
				[ "$bind_device" = "1" ] || core_cmd="${core_cmd} --bind-device false"
				[ "$kcp_proxy" = "0" ] || core_cmd="${core_cmd} --enable-kcp-proxy"
				[ "$kcp_input" = "0" ] || core_cmd="${core_cmd} --disable-kcp-input"
				[ "$proxy_forward" = "0" ] || core_cmd="${core_cmd} --proxy-forward-by-system"
				[ "$accept_dns" = "0" ] || core_cmd="${core_cmd} --accept-dns true"
				[ "$private_mode" = "0" ] || core_cmd="${core_cmd} --private-mode true"
				[ "$quic_proxy" = "0" ] || core_cmd="${core_cmd} --enable-quic-proxy"
				[ "$quic_input" = "0" ] || core_cmd="${core_cmd} --disable-quic-input"
				[ -z "$foreign_relay_bps_limit" ] || core_cmd="${core_cmd} --foreign-relay-bps-limit $foreign_relay_bps_limit"
				if [ -n "$encryption_algorithm" ] && [ "$encryption_algorithm" != "aes-gcm" ]; then
					core_cmd="${core_cmd} --encryption-algorithm ${encryption_algorithm}"
				fi
				[ -z "$extra_args" ] || core_cmd="${core_cmd} $extra_args"
	     		fi
			if [ "$sdwancmd" = "web" ] ; then
				#WEB控制台启动
				echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 运行 ${sdwanbin} -w ${web_config}" >>/tmp/sdwan.log
				[ -f /etc/sdwan/sdwan_machine_id ] || touch /etc/sdwan/sdwan_machine_id
				if [ ! -s /etc/sdwan/sdwan_machine_id ]; then
					cat /proc/sys/kernel/random/uuid > /etc/sdwan/sdwan_machine_id
					echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 生成新的 UUID 到 /etc/sdwan/sdwan_machine_id" >>/tmp/sdwan.log
				fi
				sdwan_uuid="$(cat /etc/sdwan/sdwan_machine_id | tr -d ' 
')"
				[ -z "$sdwan_uuid" ] || core_cmd="${core_cmd} --machine-id $sdwan_uuid"
				[ -z "$web_config" ] || core_cmd="${core_cmd} -w $web_config"
				[ -z "$desvice_name" ] || core_cmd="${core_cmd} --hostname $desvice_name"
			fi
	     		procd_set_param command /bin/sh -c "
			${sdwanbin} ${core_cmd} --console-log-level ${log} >> /tmp/sdwan.log 2>&1 &
			SDWAN_CORE_PID=\$!
		{
		while true; do
			LOG_SIZE=\$(ls -l /tmp/sdwan.log | awk '{print int(\$5/1024)}')
			if [ \$LOG_SIZE -gt 5120 ]; then
				tail -n 500 /tmp/sdwan.log > /tmp/sdwan.log.tmp
				mv /tmp/sdwan.log.tmp /tmp/sdwan.log
			fi
			sleep 300
		done
		} &
		LOG_MANAGEMENT_PID=\$!
		trap "kill -TERM \$SDWAN_CORE_PID; kill -TERM \$LOG_MANAGEMENT_PID; exit" SIGINT SIGTERM EXIT
		wait \$SDWAN_CORE_PID
		   	"
        	fi
		
		procd_set_param limits core="unlimited"
		procd_set_param limits nofile="1000000 1000000"
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_set_param respawn
		procd_close_instance
		
                if [ ! -z "$socks_port" ] ; then
		    echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 添加防火墙规则 sdwan_socks5 放行端口 ${socks_port} " >>/tmp/sdwan.log
		    uci -q delete firewall.sdwan_socks5
		    uci set firewall.sdwan_socks5=rule
		    uci set firewall.sdwan_socks5.name="sdwan_socks5"
		    uci set firewall.sdwan_socks5.target="ACCEPT"
		    uci set firewall.sdwan_socks5.src="wan"
		    uci set firewall.sdwan_socks5.proto="tcp"
		    uci set firewall.sdwan_socks5.dest_port="$socks_port"
		    uci set firewall.sdwan_socks5.enabled="1"
                fi
                if [ "$listenermode" = "ON" ] || [ "$sdwancmd" = "web" ] ; then
                  	if [ -z "$tcp_port" ] && [ -z "$ws_port" ] && [ -z "$wss_port" ] && [ -z "$wg_port" ] ; then
                     		tcp_port="10010"
                    		 ws_port="10011"
                    		 wss_port="10012"
                    		 wg_port="10011"
                  	fi
		fi
		set_firewall 
		sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1
                [ ! -z "$checkip" ] && check
                echo `date +%s` > /tmp/sdwan_time
		echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 启动完成!" >>/tmp/sdwan.log
}

start_web() {
	webbin="$(uci -q get sdwan.@sdwan[0].webbin)"
	if [ -f /tmp/sdwan-web-embed ] ; then
		echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 找到上传的sdwan-web程序，替换${webbin} " >>/tmp/sdwanweb.log
		mv -f /tmp/sdwan-web-embed "$webbin"
	fi
	if [ ! -f "$webbin" ] || [ "$(($($webbin -h 2>&1 | wc -l)))" -lt 3 ] ; then
		echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : $webbin 不存在或程序不完整，开始在线下载..." >>/tmp/sdwanweb.log
        	check_bin
	fi
	if [ -f "$webbin" ] ; then
		[ ! -x "$webbin" ] && chmod +x "$webbin"
	fi
	if [ ! -f "$webbin" ] || [ "$($webbin -h 2>&1 | wc -l)" -lt 3 ] ; then
		echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 未找到${webbin}程序或程序不适配当前架构，请上传安装后再启动！ " >>/tmp/sdwanweb.log
		return 1
	fi
	echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 开始启动${webbin} " >>/tmp/sdwanweb.log
	db_path="$(uci -q get sdwan.@sdwanweb[0].db_path)"
	web_protocol="$(uci -q get sdwan.@sdwanweb[0].web_protocol)"
	web_port="$(uci -q get sdwan.@sdwanweb[0].web_port)"
	api_port="$(uci -q get sdwan.@sdwanweb[0].api_port)"
	html_port="$(uci -q get sdwan.@sdwanweb[0].html_port)"
	weblog="$(uci -q get sdwan.@sdwanweb[0].weblog)"
	api_host="$(uci -q get sdwan.@sdwanweb[0].api_host)"
	geoip_db="$(uci -q get sdwan.@sdwanweb[0].geoip_db)"
	fw_web="$(uci -q get sdwan.@sdwanweb[0].fw_web || echo 0)"
	fw_api="$(uci -q get sdwan.@sdwanweb[0].fw_api || echo 0)"
	procd_open_instance "sdwan_web"
	get_tz
	[ -z "$SET_TZ" ] || procd_set_param env TZ="$SET_TZ"
	web_cmd=""
	[ -z "$db_path" ] || web_cmd="${web_cmd} -d $db_path"
	[ -z "$web_protocol" ] || web_cmd="${web_cmd} -p $web_protocol"
	[ -z "$web_port" ] || web_cmd="${web_cmd} -c $web_port"
	[ -z "$api_port" ] || web_cmd="${web_cmd} -a $api_port"
	[ -z "$api_host" ] || web_cmd="${web_cmd} --api-host $api_host"
	[ -z "$geoip_db" ] || web_cmd="${web_cmd} --geoip-db $geoip_db"
	if [ -z "$html_port" ] ; then
		web_cmd="${web_cmd} --no-web"
	else
		web_cmd="${web_cmd} -l $html_port"
	fi
	if [ "$weblog" != "off" ] ; then
		web_cmd="${web_cmd} --console-log-level $weblog"	
	fi
	procd_set_param command /bin/sh -c "
		${webbin} ${web_cmd} >> /tmp/sdwanweb.log 2>&1 &
		SDWAN_WEB_PID=\$!
		{
			while true; do
				LOG_SIZE=\$(ls -l /tmp/sdwanweb.log | awk '{print int(\$5/1024)}')
				if [ \$LOG_SIZE -gt 5120 ]; then
					tail -n 500 /tmp/sdwanweb.log > /tmp/sdwanweb.log.tmp
					mv /tmp/sdwanweb.log.tmp /tmp/sdwanweb.log
				fi
				sleep 300
			done
		} &
		LOG_MANAGEMENT_PID=\$!
		trap "kill -TERM \$SDWAN_WEB_PID; kill -TERM \$LOG_MANAGEMENT_PID; exit" SIGINT SIGTERM EXIT
		wait \$SDWAN_WEB_PID
	"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
	if [ ! -z "$web_port" ] && [ "$fw_web" = "1" ] ; then
		      echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 添加防火墙规则 sdwan_web 放行服务端口 ${web_port} " >>/tmp/sdwanweb.log
                      uci -q delete firewall.sdwan_webserver
		      uci set firewall.sdwan_webserver=rule
		      uci set firewall.sdwan_webserver.name="sdwan_webserver"
		      uci set firewall.sdwan_webserver.target="ACCEPT"
		      uci set firewall.sdwan_webserver.src="wan"
		      uci set firewall.sdwan_webserver.proto="tcp udp"
		      uci set firewall.sdwan_webserver.dest_port="$web_port"
		      uci set firewall.sdwan_webserver.enabled="1"
	fi
	if [ ! -z "$api_port" ] && [ "$fw_api" = "1" ] ; then
		      echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 添加防火墙规则 sdwan_web 放行API端口 ${api_port} " >>/tmp/sdwanweb.log
                      uci -q delete firewall.sdwan_webapi
		      uci set firewall.sdwan_webapi=rule
		      uci set firewall.sdwan_webapi.name="sdwan_webapi"
		      uci set firewall.sdwan_webapi.target="ACCEPT"
		      uci set firewall.sdwan_webapi.src="wan"
		      uci set firewall.sdwan_webapi.proto="tcp"
		      uci set firewall.sdwan_webapi.dest_port="$api_port"
		      uci set firewall.sdwan_webapi.enabled="1"
	fi
	if [ ! -z "$html_port" ] && [ "$fw_api" = "1" ] && [ "$html_port" != "$api_port" ] ; then
		      echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 添加防火墙规则 sdwan_web 放行html端口 ${html_port} " >>/tmp/sdwanweb.log
                      uci -q delete firewall.sdwan_webhtml
		      uci set firewall.sdwan_webhtml=rule
		      uci set firewall.sdwan_webhtml.name="sdwan_webhtml"
		      uci set firewall.sdwan_webhtml.target="ACCEPT"
		      uci set firewall.sdwan_webhtml.src="wan"
		      uci set firewall.sdwan_webhtml.proto="tcp"
		      uci set firewall.sdwan_webhtml.dest_port="$html_port"
		      uci set firewall.sdwan_webhtml.enabled="1"
	fi
	echo `date +%s` > /tmp/sdwanweb_time
	echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 启动完成！ " >>/tmp/sdwanweb.log
}

start_service() {
	echo "start.."
	cputype=$(uname -ms | tr ' ' '_' | tr '[A-Z]' '[a-z]')
        [ -n "$(echo $cputype | grep -E "linux.*armv.*")" ] && cpucore="arm" 
        [ -n "$(echo $cputype | grep -E "linux.*armv7.*")" ] && [ -n "$(cat /proc/cpuinfo | grep vfp)" ] && cpucore="armv7" 
        [ -n "$(echo $cputype | grep -E "linux.*aarch64.*|linux.*armv8.*")" ] && cpucore="aarch64" 
        [ -n "$(echo $cputype | grep -E "linux.*86.*")" ] && cpucore="i386" 
        [ -n "$(echo $cputype | grep -E "linux.*86_64.*")" ] && cpucore="x86_64" 
        if [ -n "$(echo $cputype | grep -E "linux.*mips.*")" ] ; then
           mipstype=$(echo -n I | hexdump -o 2>/dev/null | awk '{ print substr($2,6,1); exit}') 
           [ "$mipstype" = "0" ] && cpucore="mips" || cpucore="mipsel" 
        fi
        echo "" >/tmp/sdwan.log
	echo "" >/tmp/sdwanweb.log
        size="$(df -k | awk '/\/overlay$/ {sub(/K$/, "", $4); print $4}')"
	[ -z "$size" ] && size="$(df -k /usr/bin | awk 'NR==2 {print $(NF-2) }')"
	if [ -z "$(uci -q get sdwan.@sdwanweb[0].enabled)" ] ; then
		echo "config sdwanweb" >>/etc/config/sdwan
		echo "	option enabled '0'" >>/etc/config/sdwan
	fi
	[ "$(uci -q get sdwan.@sdwanweb[0].enabled)" = "1" ] && start_web 
	[ "$(uci -q get sdwan.@sdwan[0].enabled)" = "1" ] && start_sdwan sdwan
	echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 重载防火墙和网络配置...会出现短暂断网现象... " >>/tmp/sdwan.log
	echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : 重载防火墙和网络配置...会出现短暂断网现象... " >>/tmp/sdwanweb.log
        [ -n "$(uci changes network)" ] && uci commit network && /etc/init.d/network reload >/dev/null 2>&1
	[ -n "$(uci changes firewall)" ] && uci commit firewall && /etc/init.d/firewall reload >/dev/null 2>&1

}

stop_service() {
		echo "stop.."
		if [ "$(uci -q get sdwan.@sdwan[0].enabled)" = "0" ] ; then
                	pgrep -f sdwan_check | xargs kill -9 >/dev/null 2>&1
                	ps | grep 'sdwan-core' | grep -v grep | awk '{print $1}' | xargs kill >/dev/null 2>&1
                	ps | grep 'sdwan-core' | grep -v grep | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
                	uci -q delete network.sdwan >/dev/null 2>&1
                	uci -q delete firewall.sdwanzone >/dev/null 2>&1
	        	uci -q delete firewall.sdwanfwlan >/dev/null 2>&1
	        	uci -q delete firewall.sdwanfwwan >/dev/null 2>&1
	        	uci -q delete firewall.lanfwsdwan >/dev/null 2>&1
	        	uci -q delete firewall.wanfwsdwan >/dev/null 2>&1
	        	uci -q delete firewall.sdwan_tcp >/dev/null 2>&1
                	uci -q delete firewall.sdwan_udp >/dev/null 2>&1
                	uci -q delete firewall.sdwan_tcp_udp >/dev/null 2>&1
                	uci -q delete firewall.sdwan_wss >/dev/null 2>&1
                	uci -q delete firewall.sdwan_ws >/dev/null 2>&1
                	uci -q delete firewall.sdwan_wg >/dev/null 2>&1
                	uci -q delete firewall.sdwan_quic >/dev/null 2>&1
                	uci -q delete firewall.sdwan_wireguard >/dev/null 2>&1
                	uci -q delete firewall.sdwan_socks5 >/dev/null 2>&1
                	[ -n "$(uci changes network)" ] && uci commit network && /etc/init.d/network reload >/dev/null 2>&1
	        	[ -n "$(uci changes firewall)" ] && uci commit firewall && /etc/init.d/firewall reload >/dev/null 2>&1 
                	rm -rf /tmp/sdwan-cli_peer /tmp/sdwan-cli_connector /tmp/sdwan-cli_stun /tmp/sdwan-cli_route /tmp/sdwan-cli_acl >/dev/null 2>&1
                	rm -rf /tmp/sdwan-cli_peer-center /tmp/sdwan-cli_vpn-portal /tmp/sdwan_cmd /tmp/sdwan-cli_node /tmp/sdwan-cli_mapped_listener >/dev/null 2>&1
                	rm -rf /tmp/sdwan-*.* /tmp/sdwan.log >/dev/null 2>&1
                	echo "$(date '+%Y-%m-%d %H:%M:%S') sdwan : sdwan-core 停止运行" >>/tmp/sdwan.log
		fi
		if [ "$(uci -q get sdwan.@sdwanweb[0].enabled)" = "0" ] ; then
                	ps | grep 'sdwan-web' | grep -v grep | awk '{print $1}' | xargs kill >/dev/null 2>&1
                	ps | grep 'sdwan-web' | grep -v grep | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
			uci -q delete firewall.sdwan_webserver
			uci -q delete firewall.sdwan_webapi
			uci -q delete firewall.sdwan_webhtml
		fi
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "sdwan"
	#如果任意网络接口上线则触发重新启动sdwan
        procd_add_interface_trigger "interface.*.up" wan /etc/init.d/sdwan reload
}

